"use client";

import { useState } from "react";
import Head from "next/head";
import { useRouter } from "next/navigation";

import { doLogin } from "./services/Web3Service";

export default function Home() {
  const { push } = useRouter();

  const [message, setMessage] = useState("");

  const backgroundImageStyle = {
    backgroundImage: "url(/campeonato-brasileiro.jpg)",
    backgroundSize: "cover",
    backgroundPosition: "center",
    height: "100vh",
    width: "100vw",
    color: "white",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "space-between",
  };

  function handleConnectWallet() {
    setMessage("Connecting to wallet...please wait...");

    doLogin()
      .then((account) => push("/bet"))
      .catch((err) => {
        console.error(err);
        setMessage("Home - Login:", err.message);
      });
  }

  return (
    <>
      <div
        style={backgroundImageStyle}
        className="container d-block background-color='#0f1221' align-items-center justify-content-center mx-lg-auto px-4 py-4"
      >
        <Head>
          <title>BetCandidate | Login</title>
          <meta charSet="utf-8" />
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
        <div className="row flex-lg-row align-items-center">
          <div className="col-5 ">
            <h1 className="fw-bold text-light mx-4 mt-4">BetCandidate</h1>
            <p className="lead text-light mx-4 mt-4">
              On-chain bets on the 2025 Brazilian Championship, on the top two
              teams in the standings.
            </p>
            <p className="lead text-light mx-4 mt-4">
              Authenticate yourself with your wallet, and place your bet for the
              next contest.
            </p>
            <div className="d-grid gap-2 d-md-flex justify-content-md-start py-5 mt-5">
              <button
                type="button"
                onClick={handleConnectWallet}
                className="btn btn-primary btn-sm mx-4 px-4 me-md-2"
              >
                <img
                  src="/logo-metamask.png"
                  alt="logo metamask"
                  width={32}
                  className="me-2"
                />
                Connect with Metamask
              </button>
            </div>
          </div>
          <div className="col-7 "></div>
        </div>
        <div className="row flex-lg-row w-100 ">
          <div className="col-2"></div>
        </div>
        <p className="ml-3 mx-4 mt-4 p-1 fw-bold text-light">{message}</p>
      </div>
      <footer className="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top bottom-0">
        <p className="text-center text-light">© 2025 BetCandidate, Inc</p>
        <div className="col-4"></div>
        <ul className="nav col-5 justify-content-end list-unstyled d-flex">
          <li className="nav-item">
            <a href="/" className="nav-link text-light px-4">
              Home
            </a>
          </li>
          <li className="nav-item">
            <a href="#" className="nav-link px-4">
              Classification
            </a>
          </li>
          <li className="nav-item">
            <a href="/about" className="nav-link px-4">
              About
            </a>
          </li>
        </ul>
        <div className="col-1"></div>
      </footer>
    </>
  );
}
