"use client";

import { useState } from "react";
import Head from "next/head";

export default function Bet() {
  const [message, setMessage] = useState("");

  const backgroundImageStyle = {
    backgroundImage: "url(/campeonato-brasileiro.jpg)",
    backgroundSize: "cover",
    backgroundPosition: "center",
    height: "100vh",
    width: "100vw",
    color: "white",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "space-between",
  };

  function handleConnectWallet() {
    console.log("connect wallet");
  }

  return (
    <>
      <div
        style={backgroundImageStyle}
        className="container d-block background-color='#0f1221' align-items-center justify-content-center mx-lg-auto px-4 py-4"
      >
        <Head>
          <title>BetCandidate | Bet</title>
          <meta charSet="utf-8" />
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
        <div className="row flex-lg-row align-items-center">
          <div className="col-5 ">
            <h1 className="fw-bold text-light mx-4 mt-4">BetCandidate</h1>
            <p className="lead text-light mx-4 mt-4">
              On-chain bets on the 2025 Brazilian Championship, on the top two
              teams in the standings.
            </p>
            <p className="lead text-light mx-4 mt-4">
              You have until one day before the last round of the Brazilian
              championship to place your bets.
            </p>
            <div className="d-grid gap-2 d-md-flex justify-content-md-start py-5 mt-5"></div>
            <p className="ml-3 mt-2 mx-4 text-light"></p>
          </div>
          <div className="col-7 "></div>
        </div>
        <div className="row flex-lg-row w-100 mb-4">
          <div className="col-2"></div>
          <div className="col-4 d-block text-center">
            <img
              src="/logo-palmeiras.png"
              alt="logo do palmeiras"
              width={160}
              height={160}
              className="img-fluid"
            />
            <button className="btn btn-primary my-2 d-block mx-auto">
              Voto no Palmeiras
            </button>
            <span
              className="badge text-light my-2 text-bg-secondary d-block mx-auto"
              styles={{ width: 200 }}
            >
              0 POL bet on
            </span>
          </div>
          <div className="col-4 d-block img-fluid text-center">
            <img
              src="/logo-flamengo.png"
              alt="logo do palmeiras"
              width={160}
              height={160}
              className="img-fluid"
            />
            <button className="btn btn-primary my-2 d-block mx-auto">
              Voto no Flamengo
            </button>
          </div>
          <div className="col-2"></div>
        </div>
        <div className="row align-items-center">
          <div className="col-12">
            <p className="text-light mx-auto">{message}</p>
          </div>
        </div>
      </div>
      <footer className="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top bottom-0">
        <p className="text-center text-light">© 2025 BetCandidate, Inc</p>
        <div className="col-4"></div>
        <ul className="nav col-5 justify-content-end list-unstyled d-flex">
          <li className="nav-item">
            <a href="/" className="nav-link text-light px-4">
              Home
            </a>
          </li>
          <li className="nav-item">
            <a href="#" className="nav-link px-4">
              Classification
            </a>
          </li>
          <li className="nav-item">
            <a href="/about" className="nav-link px-4">
              About
            </a>
          </li>
        </ul>
        <div className="col-1"></div>
      </footer>
    </>
  );
}
