"use client";

import { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import Head from "next/head";
import Web3 from "web3";

import { getDispute } from "../services/Web3Service";

export default function Bet() {
  const { push } = useRouter();

  const [message, setMessage] = useState("");
  const [dispute, setDispute] = useState({
    candidate1: "Loading...",
    candidate2: "Loading...",
    image1:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Palmeiras_logo.svg/300px-Palmeiras_logo.svg.png",
    image2:
      "https://logoeps.com/wp-content/uploads/2012/11/clube-de-regatas-do-flamengo-logo-vector.png",
    total1: 0,
    total2: 0,
    winner: 0,
  });

  const backgroundImageStyle = {
    backgroundImage: "url(/campeonato-brasileiro.jpg)",
    backgroundSize: "cover",
    backgroundPosition: "center",
    height: "100vh",
    width: "100vw",
    color: "white",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "space-between",
  };

  useEffect(() => {
    if (!localStorage.getItem("addressWallet")) {
      setMessage("Metamask not connected or authorization!");
      return push("/");
    }

    setMessage("Getting dispute data...please wait...");

    getDispute()
      .then((dispute) => {
        setDispute(dispute);
        setMessage("");
      })
      .catch((err) => {
        console.error(err);
        setMessage(err.message);
      });
  }, []);

  return (
    <>
      <div
        style={backgroundImageStyle}
        className="container d-block background-color='#0f1221' align-items-center justify-content-center mx-lg-auto px-4 py-4"
      >
        <Head>
          <title>BetCandidate | Bet</title>
          <meta charSet="utf-8" />
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
        <div className="row flex-lg-row align-items-center">
          <div className="col-5 ">
            <h1 className="fw-bold text-light mx-4 mt-4">BetCandidate</h1>
            <p className="lead text-light mx-4 mt-4">
              On-chain bets on the 2025 Brazilian Championship, on the top two
              teams in the standings.
            </p>
            <p className="lead text-light mx-4 mt-4">
              You have until one day before the last round of the Brazilian
              championship to place your bets.
            </p>
            <div className="d-grid gap-2 d-md-flex justify-content-md-start py-5 mt-5"></div>
            <p className="ml-3 mt-2 mx-4 text-light"></p>
          </div>
          <div className="col-7 "></div>
        </div>
        <div className="row flex-lg-row w-100 mb-4">
          <div className="col-2"></div>
          <div className="col-4 d-block text-center">
            <img
              src={dispute.image1}
              alt={dispute.candidate1}
              width={160}
              height={160}
              className="img-fluid"
            />
            <button className="btn btn-primary my-2 d-block mx-auto">
              Voto no {dispute.candidate1}
            </button>
            <span
              className="badge text-light my-2 text-bg-secondary d-block mx-auto"
              styles={{ width: 200 }}
            >
              {Web3.utils.fromWei(dispute.total1, "ether")} POL bet on
            </span>
          </div>
          <div className="col-4 d-block img-fluid text-center">
            <img
              src={dispute.image2}
              alt={dispute.candidate2}
              width={160}
              height={160}
              className="img-fluid"
            />
            <button className="btn btn-primary my-2 d-block mx-auto">
              Voto no {dispute.candidate2}
            </button>
            <span
              className="badge text-light my-2 text-bg-secondary d-block mx-auto"
              styles={{ width: 200 }}
            >
              {Web3.utils.fromWei(dispute.total2, "ether")} POL bet on
            </span>
          </div>
          <div className="col-2"></div>
        </div>
        <div className="row align-items-center">
          <div className="col-12">
            <p className="text-light mx-auto">{message}</p>
          </div>
        </div>
        <footer className="d-flex flex-wrap text-center justify-content-center position-fixed bottom-0">
          <p className="text-center mt-2 text-light">
            © 2025 BetCandidate, Inc
          </p>

          <ul className="nav col-12 justify-content-end list-unstyled d-flex ">
            <li className="nav-item">
              <a href="/" className="nav-link text-light px-4">
                Home
              </a>
            </li>
            <li className="nav-item">
              <a href="#" className="nav-link px-4">
                Classification
              </a>
            </li>
            <li className="nav-item">
              <a href="/about" className="nav-link px-4">
                About
              </a>
            </li>
          </ul>
        </footer>
      </div>
    </>
  );
}
